spring.application.name=p2p-digital-wallet
#server.port=8080

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.jpa.open-in-view=false

#spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update