spring.datasource.url=jdbc:mysql://localhost:3306/p2p_digital_wallet?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=YOUR_MYSQL_USERNAME
spring.datasource.password=YOUR_MYSQL_PASSWORD